-- MySQL Script generated by MySQL Workbench
-- 09/18/16 18:53:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema juiced_project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema juiced_project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `juiced_project` DEFAULT CHARACTER SET utf8 ;
USE `juiced_project` ;

-- -----------------------------------------------------
-- Table `juiced_project`.`card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `juiced_project`.`card` (
  `cardid` INT NOT NULL AUTO_INCREMENT,
  `points` VARCHAR(45) NULL,
  PRIMARY KEY (`cardid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'All customers have one card.';


-- -----------------------------------------------------
-- Table `juiced_project`.`juice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `juiced_project`.`juice` (
  `juiceid` INT NOT NULL,
  `cup_size` ENUM('S', 'M', 'L') NOT NULL COMMENT 'Cup size designated into Small (S), Medium (M), Large (L).\nVolumes size represents are as follows: S=400mL, M=500mL, L=600mL.',
  PRIMARY KEY (`juiceid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `juiced_project`.`inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `juiced_project`.`inventory` (
  `inventoryid` INT NOT NULL AUTO_INCREMENT,
  `stock` INT NOT NULL,
  `date_added` DATE NOT NULL,
  `cost` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`inventoryid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `juiced_project`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `juiced_project`.`product` (
  `productid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `juiceprice(ml)` DECIMAL(2,2) NULL DEFAULT NULL COMMENT 'NOT NULL IF miscprice=NULL.',
  `miscprice` DECIMAL(2,2) NULL DEFAULT NULL COMMENT 'NOT NULL IF juiceprice(ml)=NULL.',
  `inventoryid` INT NOT NULL,
  PRIMARY KEY (`productid`),
  INDEX `inventoryid_idx` (`inventoryid` ASC),
  CONSTRAINT `inventoryid`
    FOREIGN KEY (`inventoryid`)
    REFERENCES `juiced_project`.`inventory` (`inventoryid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `juiced_project`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `juiced_project`.`cart` (
  `cartid` INT NOT NULL AUTO_INCREMENT,
  `juiceid` INT NULL COMMENT 'NOT NULL IF productid=Null',
  `productid` INT NULL COMMENT 'NOT NULL IF juiceid=Null',
  `price` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`cartid`),
  INDEX `productid_idx` (`productid` ASC),
  INDEX `juiceid_idx` (`juiceid` ASC),
  CONSTRAINT `juiceid`
    FOREIGN KEY (`juiceid`)
    REFERENCES `juiced_project`.`juice` (`juiceid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `productid`
    FOREIGN KEY (`productid`)
    REFERENCES `juiced_project`.`product` (`productid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Cart table combines miscellaneous products with juices to pool their sum prices into one column.';


-- -----------------------------------------------------
-- Table `juiced_project`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `juiced_project`.`customer` (
  `customerid` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `cardid` INT NOT NULL,
  PRIMARY KEY (`email`, `customerid`, `cardid`),
  INDEX `cardid_idx` (`cardid` ASC),
  CONSTRAINT `cardid`
    FOREIGN KEY (`cardid`)
    REFERENCES `juiced_project`.`card` (`cardid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Contains customer information';


-- -----------------------------------------------------
-- Table `juiced_project`.`store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `juiced_project`.`store` (
  `storeid` INT NOT NULL,
  `centre` VARCHAR(45) NOT NULL COMMENT 'Name of shopping centre.',
  `address` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`storeid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `juiced_project`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `juiced_project`.`transaction` (
  `transactionid` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL COMMENT 'Date of transaction.',
  `day` ENUM('monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday') NOT NULL COMMENT 'Specific day of transaction.',
  `storeid` INT NOT NULL,
  `cartid` INT NOT NULL,
  `customerid` INT NOT NULL,
  `cardid` INT NOT NULL,
  PRIMARY KEY (`transactionid`, `cartid`),
  INDEX `storeid_idx` (`storeid` ASC),
  INDEX `cartid_idx` (`cartid` ASC),
  INDEX `customerid_idx` (`customerid` ASC),
  INDEX `cardid_idx` (`cardid` ASC),
  CONSTRAINT `storeid`
    FOREIGN KEY (`storeid`)
    REFERENCES `juiced_project`.`store` (`storeid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cartid`
    FOREIGN KEY (`cartid`)
    REFERENCES `juiced_project`.`cart` (`cartid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `customerid`
    FOREIGN KEY (`customerid`)
    REFERENCES `juiced_project`.`customer` (`customerid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cardid`
    FOREIGN KEY (`cardid`)
    REFERENCES `juiced_project`.`card` (`cardid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `juiced_project`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `juiced_project`.`employee` (
  `employeeid` INT NOT NULL,
  `position` VARCHAR(45) NOT NULL COMMENT 'Formal identification of employment status.',
  `firstname` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `gender` ENUM('M', 'F', 'X') NOT NULL,
  `dob` DATE NOT NULL COMMENT 'Date of birth.',
  `transactionid` INT NOT NULL COMMENT 'Allows tracking of employees specific sales.',
  PRIMARY KEY (`employeeid`, `email`),
  INDEX `transactionid_idx` (`transactionid` ASC),
  CONSTRAINT `transactionid`
    FOREIGN KEY (`transactionid`)
    REFERENCES `juiced_project`.`transaction` (`transactionid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `juiced_project`.`ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `juiced_project`.`ingredients` (
  `percent` DECIMAL(3,0) NOT NULL COMMENT 'Percentage of products used to form a juice.',
  `juiceid` INT NOT NULL,
  `productid` INT NOT NULL,
  PRIMARY KEY (`juiceid`),
  INDEX `productid_idx` (`productid` ASC),
  CONSTRAINT `juiceid`
    FOREIGN KEY (`juiceid`)
    REFERENCES `juiced_project`.`juice` (`juiceid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `productid`
    FOREIGN KEY (`productid`)
    REFERENCES `juiced_project`.`product` (`productid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Products used to form a juice.';


-- -----------------------------------------------------
-- Table `juiced_project`.`works_at`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `juiced_project`.`works_at` (
  `percentage` DECIMAL(2,1) NOT NULL COMMENT 'Fixed percentage of time working at any given store.',
  `storeid` INT NOT NULL,
  `employeeid` INT NOT NULL,
  INDEX `storeid_idx` (`storeid` ASC),
  INDEX `eployeeid_idx` (`employeeid` ASC),
  CONSTRAINT `storeid`
    FOREIGN KEY (`storeid`)
    REFERENCES `juiced_project`.`store` (`storeid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `eployeeid`
    FOREIGN KEY (`employeeid`)
    REFERENCES `juiced_project`.`employee` (`employeeid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
